#postgres
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:35432/fit}
    username: ${SPRING_DATASOURCE_USERNAME:fit}
    password: ${SPRING_DATASOURCE_PASSWORD:fitpwd}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

bot:
  ability:
    credentials:
      creatorId: ${CREATOR_ID:134614839}
      username: ${TEST_BOT_USERNAME:1180012456:AAHvREDsUkRyO0cyCJXVngLqD8j_57pVTp8}
      token: ${TEST_BOT_TOKEN:narryelFitBot}
  health-ping: ${PING_ENABLED:false}

cron:
  every_one_minute: '0 */1 * * * *'
  every_three_minute: '0 */3 * * * *'
  every_five_minute: '0 */5 * * * *'